version: "3"

services:
  bookworm-openscad:
    image: bookworm-openscad-devcontainer
    container_name: bookworm-openscad-devcontainer_c
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - ..:/workspaces:cached
    network_mode: host


# If we just use `docker compose up`, we need to forward x11
# But here, the dev container extension does it automatically

    # environment:
    #   - DISPLAY=${DISPLAY}
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix
